name: build + publish for master

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest
    #if: contains(github.event.head_commit.message, 'web')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
            VITE_PUBLIC_FIREBASE_API_KEY=${{ secrets.VITE_PUBLIC_FIREBASE_API_KEY }}
            VITE_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_PUBLIC_FIREBASE_AUTH_DOMAIN }}
            VITE_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.VITE_PUBLIC_FIREBASE_PROJECT_ID }}
            VITE_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_PUBLIC_FIREBASE_STORAGE_BUCKET }}
            VITE_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
            VITE_PUBLIC_FIREBASE_APP_ID=${{ secrets.VITE_PUBLIC_FIREBASE_APP_ID }}

      - name: Deploy on CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: https://orderflow.gr
          app: 'orderflow'
          token: '${{ secrets.APP_TOKEN }}'
          image: 'ghcr.io/cvakratsas/orderflow:master'
